"""Tests for constants module."""

import pytest
from datetime import datetime, timedelta

import build_ai_context.constants as constants
from build_ai_context.constants import (
    extract_timestamp_from_dir_name,
    generate_timestamp,
    is_timestamp,
    local_now,
)


class TestTimestampFunctions:
    """Tests for timestamp helper functions."""

    def test_generate_timestamp_format(self):
        ts = generate_timestamp()
        # Should use local wall-clock time without a timezone suffix.
        assert len(ts) == 15
        assert ts[8] == "T"
        assert ts[:8].isdigit()
        assert ts[9:].isdigit()

    def test_is_timestamp_valid(self):
        assert is_timestamp("20260329T031811") == True
        assert is_timestamp("20260329T031811+0800") == True
        assert is_timestamp("20260329T031811-0430") == True
        assert is_timestamp("20260329T031811Z") == True
        assert is_timestamp("20260329T031811Z extra") == False
        assert is_timestamp("") == False
        assert is_timestamp("12345678T123456Z") == True

    def test_local_now_uses_system_timezone_without_permissions(self):
        current = local_now()
        assert current.tzinfo is not None
        assert current.utcoffset() is not None

    def test_local_now_falls_back_to_singapore(self, monkeypatch):
        class BrokenDateTime:
            calls = 0

            @classmethod
            def now(cls, tz=None):
                cls.calls += 1
                if tz is None:
                    raise OSError("system timezone unavailable")
                return datetime(2026, 9, 9, 12, 55, 1, tzinfo=tz)

        monkeypatch.setattr(constants, "datetime", BrokenDateTime)
        current = local_now()

        assert current.utcoffset() == timedelta(hours=8)
        assert generate_timestamp() == "20260909T125501"

    def test_extract_timestamp_from_dir_name_with_timestamp(self):
        # Directory name generated by tool
        ts = extract_timestamp_from_dir_name("exported_sources_project_20260329T031811Z")
        assert ts == "20260329T031811Z"
        local_ts = extract_timestamp_from_dir_name(
            "exported_sources_project_20260329T111811"
        )
        assert local_ts == "20260329T111811"

    def test_extract_timestamp_from_dir_name_without_timestamp(self):
        # Custom directory name without timestamp
        ts = extract_timestamp_from_dir_name("my_output")
        # Should generate a fresh timestamp (format correct)
        assert is_timestamp(ts)

    def test_extract_timestamp_from_dir_name_multiple_underscores(self):
        ts = extract_timestamp_from_dir_name("exported_sources_project_20260329T031811Z")
        assert ts == "20260329T031811Z"
        ts2 = extract_timestamp_from_dir_name("exported_sources_nowinandroid_20260329T031811Z")
        assert ts2 == "20260329T031811Z"

    def test_extract_timestamp_from_dir_name_empty(self):
        ts = extract_timestamp_from_dir_name("")
        assert is_timestamp(ts)

    def test_extract_timestamp_from_dir_name_no_underscore(self):
        ts = extract_timestamp_from_dir_name("output")
        assert is_timestamp(ts)


if __name__ == "__main__":
    pytest.main([__file__])
